package rentalHistoryAnalytic.service.impl;

import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;
import rentalHistoryAnalytic.model.RentalRecord;
import rentalHistoryAnalytic.service.DocumentService;
import rentalHistoryAnalytic.service.HistoryService;
import rentalHistoryAnalytic.service.RatingService;

@Component(service = DocumentService.class)
public class DocumentServiceImpl implements DocumentService {

    @Reference
    private HistoryService historyService;
    @Reference
    private RatingService ratingService;

    @Override
    public String generateReferenceLetter(String recordId) {
        RentalRecord record = historyService.getRecordById(recordId);
        double score = ratingService.getTrustScore(record.getTenantId());
        StringBuilder letter = new StringBuilder();
        letter.append("=== OFFICIAL REFERENCE LETTER ===\n");
        letter.append("Tenant: ").append(record.getTenantId()).append("\n");
        letter.append("Property: ").append(record.getPropertyName()).append("\n");
        if (score >= 4.5) {
            letter.append("STATUS: GOLD STAR TENANT (Highly Recommended)\n");
            letter.append("This tenant has an exceptional trust score of ").append(score).append(".\n");
        } else if (score >= 3.0) {
            letter.append("STATUS: GOOD STANDING\n");
        } else {
            letter.append("STATUS: PROBATIONARY\n");
            letter.append("Note: This tenant has a lower than average trust score.\n");
        }
        letter.append("Generated by RentSpotter.\n");
        return letter.toString();
    }
}
